#!/bin/bash
# Runs model on raw grapheme input and outputs
# TSV of grapheme \t phoneme

set -euo pipefail


readonly LANGUAGE="$1"; shift
readonly CHECKPOINT="$1"; shift
# Raw input file, with each grapheme unseparated
readonly RAW_FILE="$1"; shift
readonly OUTPUT_FILE_PARTIAL="$1"; shift

readonly ROOT="/data/echau18/loanwords/experimental/lstm-preprocess-final/checkpoints"
readonly OUTPUT_FILE="/data/echau18/loanwords/experimental/lstm-preprocess-final/predictions/${OUTPUT_FILE_PARTIAL}"

python spacify.py $RAW_FILE > "${OUTPUT_FILE}.RAW"

fairseq-interactive "loanwords-data-cleaned-bin/${LANGUAGE}" \
    --source-lang "${LANGUAGE}.graphemes" \
    --target-lang "${LANGUAGE}.phonemes" \
    --path "${ROOT}/${CHECKPOINT}" \
    --beam 5 \
    --input "${OUTPUT_FILE}.RAW" \
    --tokenizer space \
    > "${OUTPUT_FILE}.TEMP"

paste \
    <(cat "${OUTPUT_FILE}.RAW" | cut -f2 | sed 's/ //g') \
    <(cat "${OUTPUT_FILE}.TEMP" | grep '^H-' | cut -f3) \
    > $OUTPUT_FILE

rm -f "${OUTPUT_FILE}.TEMP" "${OUTPUT_FILE}.RAW"

